name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. AWS CLI 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # 3. 빌드 파일 압축 (HTML과 스크립트 포함)
    - name: Archive application
      run: zip -r project.zip .  # 모든 파일 압축

    # 4. S3에 파일 업로드
    - name: Upload to S3
      run: aws s3 cp project.zip s3://my-app-bucket/project.zip  # S3 버킷 이름 수정

    # 5. CodeDeploy 배포 트리거
    - name: Deploy to EC2 via CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name my-frontend-app \
          --deployment-group-name my-frontend-group \
          --s3-location bucket=my-app-bucket,bundleType=zip,key=project.zip \
          --region ap-northeast-2
